### PR TITLE
actually include LICENSE.txt

### PR DESCRIPTION
**Pull request by djsutherland**
I messed up in #10 and tried to include `LICENSE` instead of the actual file, `LICENSE.txt`. Whoops....

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Never mind, I was looking at the wrong thing.

**Comment by dougalsutherland** [comment]
That said, [`easywatch-0.0.4.tar.gz`](https://files.pythonhosted.org/packages/49/da/53f2811f6ae3f8b06e6a804dd9b75a9c9f1ddcdc47495469d11351901991/easywatch-0.0.4.tar.gz`) doesn't have `LICENSE` in it, and I don't understand why not. When I run `setup.py sdist` locally, it does, so something was weird when you released it for some reason....

**Comment by Ceasar** [comment]
Oh oops, I merged your commit after I released 0.0.4. I just released 0.0.5 with your commit in it.

**Comment by djsutherland** [comment]
Oh, makes sense. Thanks! :)

**Pull request closed without merging**
